### ISSUE TITLE
TaskunLogLog4jImpl use commons-logging instead of log4j

### ISSUE THREAD

**Issue by namutaka** [seratch/taskun#5]
I think `TaskunLogLog4jImpl` don't use log4j.
This class means `TaskunLogCommonsLoggingImpl`.

**Comment by seratch** [comment]
Indeed, the impl class depends on only commons-logging interface. But the library, taskun-log4j-extension, depends on log4j in compile scope. So actually the class implements commons-logging interface with log4j. I think naming it Log4jImpl should be acceptable.

**Comment by namutaka** [comment]
I see. It uses log4j module actually.
